services:
  db:
    image: mysql:lts
    container_name: ${SITENAME}-mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${SITENAME}-wordpress
    environment: 
      WEB_DOCUMENT_ROOT: /app/web
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - "80:80"

volumes:
  db_data: