services:
  db:
    image: mariadb:lts
    container_name: ${SITENAME}-mariadb
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${SITENAME}-wordpress
    volumes:
      - ./:/var/www/html:cached
    depends_on:
      - db
    ports:
      - "9000:9000"
      - "9001:9003"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  nginx:
    image: nginx:alpine-slim
    container_name: ${SITENAME}-nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html:cached
    depends_on:
      - wordpress

volumes:
  db_data: